## These two functions are an example of how to cache potentially time-consuming 
## computations in R by taking advantage of the scoping rules of the R language

## This function, makeCacheMatrix, creates a special vector in the form of a matrix
## that sets the value of the matrix and calculates in inverse, saving the
## inverse value in the cache

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) m <<- inverse
        getinverse <- function() m
        list(set = set,
             get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## This function computes the inverse of the special "matrix" generated by makeCacheMatrix above. 
## If the inverse has already been calculated it retrieves it from the cache 


cacheSolve <- function(x, ...) {
        m <- x$getinverse()
        if (!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinverse(m)
        m
}